### PR TITLE
Restore old ownership ui + modify button

### LINKED ISSUE #863: Ownership panel is confusing
The ownership panel on a dandiset just says "Ownership", then presents a search box and several chips with usernames. It's not self-evident what to do with this, nor how to effect changes.

### PR DESCRIPTION
**Pull request by mvandenburgh**
Partially fixes #863.

For the most part, this PR just restores the old ownership management dialog, which is closer to what Jared's new design looks like. Per the new design, I also moved the "Manage Ownership" button to underneath the owner list and restyled it.

I will make a follow-up PR that actually implements Jared's design in it's entirety. Since the new design is a major change to how we handle ownership management in the UI, I'd like to do this incrementally in the interest of keeping PR diff sizes low.

### CODE REVIEW

**Comment by waxlamp** [comment]
> Since the new design is a major change to how we handle ownership management in the UI, I'd like to do this incrementally in the interest of keeping PR diff sizes low.

I appreciate this goal, but the cost is a shifting design in production in between PRs. Can we try for the best of both worlds with a sequence of PRs targeted to a longer-lived feature branch to capture the changes in one meta-PR?

**Comment by mvandenburgh** [comment]
> > Since the new design is a major change to how we handle ownership management in the UI, I'd like to do this incrementally in the interest of keeping PR diff sizes low.
> 
> I appreciate this goal, but the cost is a shifting design in production in between PRs. Can we try for the best of both worlds with a sequence of PRs targeted to a longer-lived feature branch to capture the changes in one meta-PR?

Sounds good :+1:

I'll mark this as draft for now.

**Comment by waxlamp** [comment]
> > > Since the new design is a major change to how we handle ownership management in the UI, I'd like to do this incrementally in the interest of keeping PR diff sizes low.
> > 
> > 
> > I appreciate this goal, but the cost is a shifting design in production in between PRs. Can we try for the best of both worlds with a sequence of PRs targeted to a longer-lived feature branch to capture the changes in one meta-PR?
> 
> Sounds good +1
> 
> I'll mark this as draft for now.

If it's ready for review, you can just create a new branch (something like `ownership-ui`) and just target this PR to that branch. Then we can review and merge without needing to deploy the change. Let me know if that's a good plan.

**Comment by mvandenburgh** [comment]
> > > > Since the new design is a major change to how we handle ownership management in the UI, I'd like to do this incrementally in the interest of keeping PR diff sizes low.
> > > 
> > > 
> > > I appreciate this goal, but the cost is a shifting design in production in between PRs. Can we try for the best of both worlds with a sequence of PRs targeted to a longer-lived feature branch to capture the changes in one meta-PR?
> > 
> > 
> > Sounds good +1
> > I'll mark this as draft for now.
> 
> If it's ready for review, you can just create a new branch (something like `ownership-ui`) and just target this PR to that branch. Then we can review and merge without needing to deploy the change. Let me know if that's a good plan.

Sounds good, I did as you suggested.

**Review by dchiquito — APPROVED** [review]

**Pull request merged**
