### PR TITLE
Hide "Log In With Github" button when the page is embedded inside an iframe

### LINKED ISSUE #745: Handle specific DOMException when dandiarchive is hosted in an iframe
visiting https://dandiarchive.org which forwards to web ui, if page is embedded within iframe (trying to prepare for the virtual OHBM 2021 booth) leads to

```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new t (https://gui.dandiarchive.org/js/chunk-vendors.107d6d4a.js:101:59792)
    at new e (https://gui.dandiarchive.org/js/chunk-vendors.107d6d4a.js:29:55236)
    at new e (https://gui.dandiarchive.org/js/chunk-vendors.107d6d4a.js:29:58845)
    at Module.cd49 (https://gui.dandiarchive.org/js/app.83c9bcaf.js:1:12834)
    at s (https://gui.dandiarchive.org/js/app.83c9bcaf.js:1:564)
    at Object.0 (https://gui.dandiarchive.org/js/app.83c9bcaf.js:1:1562)
    at s (https://gui.dandiarchive.org/js/app.83c9bcaf.js:1:564)
    at n (https://gui.dandiarchive.org/js/app.83c9bcaf.js:1:431)
    at https://gui.dandiarchive.org/js/app.83c9bcaf.js:1:1527
    at https://gui.dandiarchive.org/js/app.83c9bcaf.js:1:1532
```
so the question is either we need access to the entire `Window` or it could be avoided?

### PR DESCRIPTION
**Pull request by mvandenburgh**
The `iframe` crashes if the login button is clicked when inside. This PR makes it so the `LOG IN WITH GITHUB` button is hidden when the page is embedded in an `iframe`. I also deleted any DJANGO_API feature toggle code that was related to the changes I made.

Closes #745

### CODE REVIEW

**Comment by yarikoptic** [comment]
question: it is expected to not be able to login in the netlify preview?  I am getting
```
Error: invalid_request
Mismatching redirect URI.
```
when I try to login at https://deploy-preview-750--gui-dandiarchive-org.netlify.app/#/

unfortunately doesn't work for me . Tried and getting similar
```
storage.js:50 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new t (https://deploy-preview-750--gui-dandiarchive-org.netlify.app/js/chunk-vendors.a3709087.js:101:59792)
    at new e (https://deploy-preview-750--gui-dandiarchive-org.netlify.app/js/chunk-vendors.a3709087.js:29:55236)
    at new e (https://deploy-preview-750--gui-dandiarchive-org.netlify.app/js/chunk-vendors.a3709087.js:29:58845)
    at Module.cd49 (https://deploy-preview-750--gui-dandiarchive-org.netlify.app/js/app.7c8dfbba.js:1:12742)
    at s (https://deploy-preview-750--gui-dandiarchive-org.netlify.app/js/app.7c8dfbba.js:1:564)
    at Object.0 (https://deploy-preview-750--gui-dandiarchive-org.netlify.app/js/app.7c8dfbba.js:1:1562)
    at s (https://deploy-preview-750--gui-dandiarchive-org.netlify.app/js/app.7c8dfbba.js:1:564)
    at n (https://deploy-preview-750--gui-dandiarchive-org.netlify.app/js/app.7c8dfbba.js:1:431)
    at https://deploy-preview-750--gui-dandiarchive-org.netlify.app/js/app.7c8dfbba.js:1:1527
    at https://deploy-preview-750--gui-dandiarchive-org.netlify.app/js/app.7c8dfbba.js:1:1532
```

**Comment by yarikoptic** [comment]
per "in-slack" troubleshooting my problem seems to boil down to not allowing third-party cookies!  if I allow the LocalStorage for this preview -- it loads fine and without login 

image

so it is not about "IFrame" per se I guess but about cookies being allowed or not.  could we check for that instead and display "Enable cookies to login" or smth like that?

**Comment by yarikoptic** [comment]
BTW -- allowing the cookie shows the website without the login button: my point is that all this "cookie business" is happening outside the conditioning on IFrame introduced in this PR.

**Comment by AlmightyYakob** [comment]
> question: it is expected to not be able to login in the netlify preview? I am getting
> 
> ```
> Error: invalid_request
> Mismatching redirect URI.
> ```
> 
> when I try to login at https://deploy-preview-750--gui-dandiarchive-org.netlify.app/#/

Login doesn't work on any netlify deploy previews, so this is not specific to this PR.

**Review by AlmightyYakob — APPROVED** [review]
LGTM, tested in an iframe with no issue :+1:

**Pull request merged**
