### PR TITLE
Display stats under item title

### LINKED ISSUE #396: stats feature
@AlmightyYakob - love the stats feature.

here just suggesting a potential change. in the public datasets dashboard page, could the files and size be added to the subtitle line. right after the identifier?  (i think that will also help with the wrapping on smaller devices)

image

### PR DESCRIPTION
**Pull request by AlmightyYakob**
Fixes #396 

Additional changes:
- Change the ordering of subtitle items
- Change the size icon from `server` to `database`

### CODE REVIEW

**Comment by satra** [comment]
looks great. thank you @AlmightyYakob

**Comment by satra** [comment]
@dchiquit - where are you seeing units being wrapped around? this is i think what's fixed in this PR?

**Comment by AlmightyYakob** [comment]
It occurs at very specific breakpoints, and was already there before this change. I wasn't exactly sure how to fix it, I'm not too good with small styling details like that. If we think this is a blocker I can try to fix it before merging.

**Comment by mgrauer** [comment]
I much prefer the style where the stats are displayed along with the other metadata as the dandiset subtitle, I think it is easier to see which stats go with which dandiset.

Screen Shot 2020-06-13 at 11 34 31 AM

With the separated stats, I have a hard time tracking which stats go with which dandiset, and I find it jarring that the stats move between UI elements at different breakpoints

Screen Shot 2020-06-13 at 11 41 16 AM



So I propose removing the breakpoint and only having the stats appear in the dandiset subtitle. This should also address @dchiquit 's concern.

**Comment by AlmightyYakob** [comment]
I agree with @mgrauer's comment. As long as it's okay with @satra, I can remove the right side stats and just display them on the subtitle

**Comment by satra** [comment]
@AlmightyYakob - ha! difference of field of view. i didn't even go that far out - that's why i could not understand what @dchiquit was saying. yes, no need to float those stats out. they can just be in the subtitle.

**Pull request merged**
