### PR TITLE
fix: reporting TiB

### LINKED ISSUE #649: Tebi (TiB) vs Tera (TB) bytes
i think the UI is converting size to tebi bytes (2^40) but showing TB. we could divide by 10^12 and show TB. i just thing it would be good to be consistent between size calculation and units.

### PR DESCRIPTION
**Pull request by satra**
closes #649

### CODE REVIEW

**Comment by satra** [comment]
@dchiquito or @AlmightyYakob - if you could review and merge this, that would be great :)

**Comment by satra** [comment]
hold that thought - technically this should be fixed for all places where size is being reported (dandisets listing, dandiset metadata). @sanuann - can you take a stab at this?

**Comment by satra** [comment]
@waxlamp - this is also ready for review/merge.

**Review by AlmightyYakob — APPROVED** [review]

**Comment by satra** [comment]
thanks @AlmightyYakob

**Pull request merged**
