### PR TITLE
Switch to refactored UI

### PR DESCRIPTION
**Pull request by mgrauer**
As there are no longer any release blockers on the UI side, merging refactor into master should move us to the refactored UI. We want to wait for the CLI to be changed to be in sync though, which is #308.

### CODE REVIEW

**Comment by satra** [comment]
@mgrauer - now that @yarikoptic has updated CLI, we may be able to make this switch now. are there any blockers left? 

also wdyt of dandiarchive.org pointing directly to the data portal, now that this refactor is done.

**Comment by yarikoptic** [comment]
note that I have not released `dandi-cli` yet.  I also want to explicitly bring your attention to https://github.com/dandi/dandiarchive/issues/316 (not a blocker here) so we could enhance `dandi-cli` so it could alert users when a newer version needs to be used etc.

**Comment by mgrauer** [comment]
>also wdyt of dandiarchive.org pointing directly to the data portal, now that this refactor is done.

i think this would break the redirection service, and so we couldn't support our dandiset permalinks.

**Comment by satra** [comment]
> i think this would break the redirection service, and so we couldn't support our dandiset permalinks.

the top level redirect (https://github.com/dandi/redirector/blob/master/serve.py#L18) is separate from the permalink redirect (https://github.com/dandi/redirector/blob/master/serve.py#L33).

**Comment by mgrauer** [comment]
Got it, this seems reasonable then.

You are suggesting the following?

- www.dandiarchive.org would redirect to the about static page
- dandiarchive.org would redirect to gui.dandiarchive.org, which could get to the about static page from the `about` link
- the permalink for dandisets will still go to the redirector, which will query the backend and redirect to the place in the new gui


Let's also tweak the data portal link back to the gui (I'll do this in a separate PR on the static site)

**Comment by mgrauer** [comment]
>Let's also tweak the data portal link back to the gui (I'll do this in a separate PR on the static site)

I have this PR, https://github.com/dandi/dandi.github.io/pull/24, but I see it is not necessary as the `dandiset/drafts` [route will be redirected to the GUI](https://github.com/dandi/redirector/blob/master/serve.py#L27-L31).

Is there any reason to support this `dandiset/drafts` route now or can we remove that from the redirector? Especially as it isn't going to a listing of drafts and we no longer have a listing of dandisets that are only drafts.

**Pull request merged**
