### PR TITLE
Citation and filepath fix

### LINKED ISSUE #599: DJANGO_API: Double / / if have 3rd level directory
See current test ds https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/010000/draft/files?location=sub-1%2Fsub-1_ses-10_cell-1.z%2F (goes a bit further than our 2 level `dandi organize`'ed datasets, as eg might happen later with zarr or any BIDS dataset with sessions)

image

### PR DESCRIPTION
**Pull request by sanuann**
- added list of contributors above description
- todo: add citation button
- fixes #599, #645

### CODE REVIEW

**Comment by yarikoptic** [comment]
I wonder why netlify preview isn't appearing. I see only "Expected — Waiting for status to be reported" @dandi/dandiarchive  - any clue?

**Comment by waxlamp** [comment]
> I wonder why netlify preview isn't appearing. I see only "Expected — Waiting for status to be reported" @dandi/dandiarchive - any clue?

I am not sure, but my guess is because this PR is coming from @sanuann's fork of the dandiarchive repo. The netlify build log just has one line, `Deploy request is pending review`. Sanu, did you receive any notification about that "pending review"? (I myself did not.)

@sanuann as an experiment can you try pushing your changes to a branch within this repository, and opening another PR from that? Then we'll see if the netlify preview builds as expected.

**Review by waxlamp — CHANGES_REQUESTED** [review]
Looks good! Just a couple of suggestions.

**Comment by sanuann** [comment]
> > I wonder why netlify preview isn't appearing. I see only "Expected — Waiting for status to be reported" @dandi/dandiarchive - any clue?
> 
> I am not sure, but my guess is because this PR is coming from @sanuann's fork of the dandiarchive repo. The netlify build log just has one line, `Deploy request is pending review`. Sanu, did you receive any notification about that "pending review"? (I myself did not.)
> 
> @sanuann as an experiment can you try pushing your changes to a branch within this repository, and opening another PR from that? Then we'll see if the netlify preview builds as expected.

No, I didn't receive any notification. I'll try what you suggested above.

**Comment by satra** [comment]
merging into a new branch on dandiarchive.

**Pull request merged**
