### PR TITLE
Show correct last-modified time in dandiset detail panel

### LINKED ISSUE #825: "Last updated" field shows current datetime
image

The "Last updated" field shows the current datetime. When I refresh the page, the last updated field changes to the now current datetime, even though we are not making any changes to the dataset.

### PR DESCRIPTION
**Pull request by waxlamp**
The non-existent `updated` property was previously being passed to
momentjs as the last modified date. Since that value was always
`undefined`, and momentjs returns the current date and time when called
without arguments (or with `undefined`, apparently), this explains why
the frontend was always showing the current time for the last modified
value.

Closes #825.

### CODE REVIEW

**Comment by waxlamp** [comment]
@bendichter, take a look at https://deploy-preview-826--gui-dandiarchive-org.netlify.app/#/ to see the fix in action (on staging data, so you won't see your dandisets there).

**Review by mvandenburgh — APPROVED** [review]
Looks like another bug introduced by a schema change that went unnoticed. LGTM

**Comment by bendichter** [comment]
lgtm, thanks @waxlamp

**Comment by waxlamp** [comment]
> Looks like another bug introduced by a schema change that went unnoticed. LGTM

More reason to be adopting more TypeScript and Composition API in this project.

**Pull request merged**
