### PR TITLE
Expect Python >= 3.7

### PR DESCRIPTION
**Pull request by brianhelba**
Most of the test and deployment architecture seems to target Python 3.7. This ensures a minimum Python version, which requires developers to run Python 3.7+, but allows new language features to safely be used in code.

### CODE REVIEW

**Comment by brianhelba** [comment]
This may cause disruption to developers and deployments running Ubuntu 18.04, so we should discuss before merging.

**Comment by dchiquit** [comment]
I use Ubuntu and my virtual environment is currently on 3.6.9. However I see no problem with requiring a higher version, I will be reinstalling my environment in the next week anyway.

**Comment by mgrauer** [comment]
Our production deployment is currently 3.6.8/18.04.

**Comment by brianhelba** [comment]
Closing in favor of #226

**Pull request closed without merging**
